---
title: "Exercises from Data Analysis for the Life Sciences, p. 13"
subtitle: "Brief Introduction to dplyr"
output: html_notebook
---
**Textbook:**
http://genomicsclass.github.io/book/

**[This tutorial](https://github.com/genomicsclass/labs/blob/master/intro/dplyr_tutorial.Rmd) is longer and more detailed than the text.**

*1. Read in the msleep_ggplot2.csv file with the function read.csv and use the function class to determine what type of object is returned.*

*2. Now use the filter function to select only the primates. How many animals in the table are primates? Hint: the nrow function gives you the number of rows of a data frame or matrix.*

*3. What is the class of the object you obtain after subsetting the table to only include primates?*

*4. Now use the select function to extract the sleep (total) for the primates. What class is this object? Hint: use %>% to pipe the results of the filter function to select.*

*5. Now we want to calculate the average amount of sleep for primates (the average of the numbers computed above). One challenge is that the mean function requires a vector so, if we simply apply it to the output above, we get an error. Look at the help file for unlist and use it to compute the desired average.*

*6. For the last exercise, we could also use the dplyr summarize function. We have not introduced this function, but you can read the help file and repeat exercise 5, this time using just filter and summarize to get the answer.*

```{r}
```


